table Cat_Other
	lineageTag: 5172a3ee-a715-41f2-a69a-1f809bd558ff

	column เลขหมวดสินค้า
		dataType: int64
		formatString: 0
		lineageTag: 1eae72b3-3fc2-451e-9033-2e79edfa8d8d
		summarizeBy: sum
		sourceColumn: เลขหมวดสินค้า

		annotation SummarizationSetBy = Automatic

	column หมวดสินค้า
		dataType: string
		lineageTag: 90916fd5-ab29-46fe-b8e2-31d6ccfc9f6d
		summarizeBy: none
		sourceColumn: หมวดสินค้า

		annotation SummarizationSetBy = Automatic

	partition Cat_Other = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WsrRU0lF6sGPtgx3bH+zseLBj5oOdbQoaD3a2PNixECyw+MGODQ92zHqwY4emUmwsAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [เลขหมวดสินค้า = _t, หมวดสินค้า = _t]),
				  #"Changed column type" = Table.TransformColumnTypes(Source, {{"เลขหมวดสินค้า", Int64.Type}, {"หมวดสินค้า", type text}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

