table Stock
	lineageTag: dd44e251-0d7b-440d-9842-1e95405f20a7

	measure จำนวนสินค้าทั้งหมด = DISTINCTCOUNT(Stock[รหัสสินค้า])
		formatString: #,0
		lineageTag: 0486afc6-2de5-4abf-902e-84403e6ca774

	column รหัสสินค้า
		dataType: string
		lineageTag: a087ef2d-e377-4ff5-8580-a9df084a78ac
		summarizeBy: none
		sourceColumn: รหัสสินค้า

		annotation SummarizationSetBy = Automatic

	column ชื่อสินค้า
		dataType: string
		lineageTag: 6c785676-9f22-4369-9049-d6af0befdb94
		summarizeBy: none
		sourceColumn: ชื่อสินค้า

		annotation SummarizationSetBy = Automatic

	column หมวดสินค้า
		dataType: string
		lineageTag: 1f4b0d3a-7264-4818-b2d9-f33f07622114
		summarizeBy: none
		sourceColumn: หมวดสินค้า

		annotation SummarizationSetBy = Automatic

	column คลัง
		dataType: string
		lineageTag: 1831cdd8-674c-4813-800b-b66cb47ee5c0
		summarizeBy: none
		sourceColumn: คลัง

		annotation SummarizationSetBy = Automatic

	column จำนวน
		dataType: int64
		formatString: #,0
		lineageTag: 3f725907-9b8e-472e-9718-630bc7e0510e
		summarizeBy: sum
		sourceColumn: จำนวน

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column ราคาต่อหน่วย
		dataType: double
		lineageTag: fc55bc16-ceb4-4ee3-8b44-915878c277f8
		summarizeBy: sum
		sourceColumn: ราคาต่อหน่วย

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ยอดขายรวม
		dataType: int64
		formatString: #,0
		lineageTag: b885415c-b830-4fb0-9d67-0b8fe3061d4f
		summarizeBy: sum
		sourceColumn: ยอดขายรวม

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column วันที่รับเข้าล่าสุด
		dataType: dateTime
		formatString: Long Date
		lineageTag: 639d42c8-4d60-4e37-bbc4-94dd076eefc6
		summarizeBy: none
		sourceColumn: วันที่รับเข้าล่าสุด

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'อายุสต็อก (วัน)'
		dataType: string
		lineageTag: 8e9b8a29-020b-4176-9b54-37ae97c4d0d6
		summarizeBy: none
		sourceColumn: อายุสต็อก (วัน)

		annotation SummarizationSetBy = Automatic

	column ช่วงอายุสินค้า
		dataType: string
		lineageTag: 2681dc70-b516-48d4-b19a-438c0325449e
		summarizeBy: none
		sourceColumn: ช่วงอายุสินค้า

		annotation SummarizationSetBy = Automatic

	column สถานะสินค้า
		dataType: string
		lineageTag: accf2184-d86e-433f-bcd2-d983ec2cc4cf
		summarizeBy: none
		sourceColumn: สถานะสินค้า

		annotation SummarizationSetBy = Automatic

	column สถานะสต๊อก =
			SWITCH(
			    TRUE(),
			    'Stock'[จำนวน] <= 10, "Low",
			    'Stock'[จำนวน] <= 50, "Medium",
			    "High"
			)
		lineageTag: 27d0e524-7c25-472c-8390-191dcc3bb354
		summarizeBy: none
		sortByColumn: ลำดับสถานะ

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column ลำดับสถานะ =
			
			SWITCH(
			    TRUE(),
			    'Stock'[จำนวน] <= 10, 3,
			    'Stock'[จำนวน] <= 50, 2,
			    1
			)
		formatString: 0
		lineageTag: 53c207c9-74f3-4e59-80ff-ac979caad056
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Column =
			SWITCH(
			    TRUE(),
			    'Stock'[จำนวน] <= 0, 3,
			    'Stock'[จำนวน] <= 0, 2,
			    1
			)
		formatString: #,0
		lineageTag: d17ed094-1c71-420e-82cb-9297ab31b7e6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'อายุสต็อก (วัน)2' = DATEDIFF('Stock'[วันที่รับเข้าล่าสุด], TODAY(), DAY)
		formatString: 0
		lineageTag: 06d08d43-b4ad-448d-b03c-c3617431e371
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Stock = m
		mode: import
		source =
				let
				  แหล่งข้อมูล = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1uJE0MRJYEU3C-6z7toEiAOKYGQGQENtd28-TatATuN0/edit?usp=sharing"),
				    Stock_Table = แหล่งข้อมูล{[name="Stock",ItemKind="Table"]}[Data],
				    ส่วนหัวที่เลื่อนระดับ = Table.PromoteHeaders(Stock_Table, [PromoteAllScalars=true]),
				    เปลี่ยนแปลงชนิดแล้ว = Table.TransformColumnTypes(ส่วนหัวที่เลื่อนระดับ,{{"รหัสสินค้า", type text}, {"ชื่อสินค้า", type text}, {"คลัง", type text}}),
				    กรองแถวแล้ว = Table.SelectRows(เปลี่ยนแปลงชนิดแล้ว, each ([คลัง] <> "05 ตัวอย่างทดสอบ" and [คลัง] <> "311 Thanakrit-Order" and [คลัง] <> "321 Kritamorn-Order" and [คลัง] <> "325 Kritamorn-Test" and [คลัง] <> "361 Tawatchai-Order" and [คลัง] <> "365 Tawatchai-Test" and [คลัง] <> "371 Warin-Order" and [คลัง] <> "381 Kanchaithanat - Order" and [คลัง] <> "391 PICHAI-Order" and [คลัง] <> "395 PICHAI-Test" and [คลัง] <> "421 Natphinya-Order" and [คลัง] <> "435 Audon-Test" and [คลัง] <> "471 PHATTHIYA-ORDER" and [คลัง] <> "475 PHATTHIYA-TEST" and [คลัง] <> "511 ARNON-ORDER" and [คลัง] <> "515 ARNON-TEST" and [คลัง] <> "541 Nuttapong - order" and [คลัง] <> "551 Siwaporn - order" and [คลัง] <> "561 Artit - order" and [คลัง] <> "565 Artit - Test" and [คลัง] <> "571 Kotchasorn - order" and [คลัง] <> "575 Kotchasorn - Test" and [คลัง] <> "581 Panya - Order" and [คลัง] <> "585 Panya - Test" and [คลัง] <> "591 Ravimol-Order" and [คลัง] <> "595 Ravimol-Test" and [คลัง] <> "611 Tapphon order" and [คลัง] <> "615 Tapphon Test" and [คลัง] <> "621 Jakkapong Order" and [คลัง] <> "631 Narongsak Order" and [คลัง] <> "635-Narongsak-Test" and [คลัง] <> "661 SAHAPHON-ORDER" and [คลัง] <> "665 SAHAPHOL - TEST")),
				    #"Replaced Value" = Table.ReplaceValue(กรองแถวแล้ว,"NULL","",Replacer.ReplaceValue,{"วันที่รับเข้าล่าสุด"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"วันที่รับเข้าล่าสุด", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = การนำทาง

	annotation PBI_ResultType = Table

